server.port=8081
spring.application.name=productos-service

# H2 Console (para desarrollo)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Base de datos en memoria
spring.datasource.url=jdbc:h2:mem:shopsmart_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
